- id: check-config
  stages: [commit]
  name: Check prometheus config files
  description: Check prometheus config files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: ^$
  args:
  - check
  - config

- id: check-rules
  stages: [commit]
  name: Check prometheus rule files
  description: Check prometheus rule files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: ^$
  args:
  - check
  - rules

- id: test-rules
  stages: [commit]
  name: Unit test prometheus rule files
  description: Unit test prometheus rule files
  language: docker_image
  entry: --entrypoint /bin/promtool prom/prometheus:latest
  files: ^$
  args:
  - test
  - rules

- id: check-coverage
  stages: [commit]
  name: Coverage of unit test prometheus rule files
  description: Coverage of unit test prometheus rule files
  language: script
  entry: bin/prom_coverage.rb
  type: [ruby]
  args:
    - ../chef-cookbooks/cookbooks/pprometheus_v2/files/default/alerts
    - ../chef-cookbooks/cookbooks/pprometheus_v2/files/default/unit-tests
    - '80'
    - rabbitmq.yml
    - redis.yml
    - postgres.yml
    - win_systems.yml
    - vmware.yml
    - networking.yml
    - stparser-assets.yml
